export type DietDayTarget = {
  id: string;
  username: string;
  date: string;
  energy: string;
  fat: string;
  saturates: string;
  carbohydrate: string;
  sugars: string;
  fibre: string;
  protein: string;
  salt: string;
  energy_per_kg: string;
  protein_per_kg: string;
  carbohydrate_per_kg: string;
  fat_per_kg: string;
  protein_pct: string;
  carbohydrate_pct: string;
  fat_pct: string;
};
