export type Food = {
  id: string;
  name: string;
  slug: string;
  brand_id: string;
  brand_name: string;
  brand_slug: string;
  data_value: number;
  data_measurement: string;
  energy: string;
  fat: string;
  saturates: string;
  carbohydrate: string;
  sugars: string;
  fibre: string;
  protein: string;
  salt: string;
  protein_pct: string;
  carbohydrate_pct: string;
  fat_pct: string;
};
